// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TickAggregator.Infrastructure.Database;

#nullable disable

namespace TickAggregator.Infrastructure.Database.Migrations
{
    [DbContext(typeof(TickDbContext))]
    partial class TickDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TickAggregator.Domain.Entities.Tick", b =>
                {
                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exchange");

                    b.Property<string>("TradeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trade_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("volume");

                    b.HasKey("Exchange", "TradeId");

                    b.HasIndex("Exchange", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("ticks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
